/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;
import javax.swing.JOptionPane;
import jpl.*;

/**
 *
 * @author silvia
 */
public class VentanaConsultas extends javax.swing.JDialog {
    Consulta consult = new Consulta();
    ArrayList<String> listaFechas = new ArrayList<>();
    
    /**
     * Creates new form VentanaConsultas
     */
    public VentanaConsultas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Tabla.setVisible(false);
        
        labelPadecimientos.setVisible(false);
        padecimiento.setVisible(false);
        labelAreaP.setVisible(false);
        areaPadecimiento.setVisible(false);
        fecha.setVisible(false);
        
        labelFecha.setVisible(false);
        
        
        labelDoctor.setVisible(false);
        doctor.setVisible(false);
        labelAreaTrabajo.setVisible(false);
        areaTrabajo.setVisible(false);
        labelCatidadPacientes.setVisible(false);
        cantidad.setVisible(false);
        
        labelIdentificacion.setVisible(false);
        identificacion.setVisible(false);
        labelNombre.setVisible(false);
        nombre.setVisible(false);
        labelEdad.setVisible(false);
        edad.setVisible(false);
        labelGenero.setVisible(false);
        genero.setVisible(false);
        labelTelefono.setVisible(false);
        telefono.setVisible(false);
        labelPadecimientoPaciente.setVisible(false);
        padecimientoPaciente.setVisible(false);
        labelIntensidad.setVisible(false);
        intensidad.setVisible(false);
        

        padecimiento.removeAllItems();
        padecimiento.addItem("Padecimientos");
        
        padecimientoPaciente.removeAllItems();
        padecimientoPaciente.addItem("Padecimientos");
        
        areaPadecimiento.removeAllItems();
        areaPadecimiento.addItem("Areas");
        
        areaTrabajo.removeAllItems();
        areaTrabajo.addItem("Areas");
        
        doctor.removeAllItems();
        doctor.addItem("Doctores");

        cantidad.removeAllItems();
        cantidad.addItem("Pacientes");
        
        ArrayList<String> listaPadecimientos = new ArrayList<>();
        listaPadecimientos = consult.getPadecimientos();
        
        for(int i = 0; i < listaPadecimientos.size(); i++){
            padecimiento.addItem(listaPadecimientos.get(i));
            padecimientoPaciente.addItem(listaPadecimientos.get(i));
        }
        

        ArrayList<String> listAreas = new ArrayList<String>();
        listAreas = consult.getAreas();
        
        for(int i = 0; i < listAreas.size(); i++){
            areaPadecimiento.addItem(listAreas.get(i));
            areaTrabajo.addItem(listAreas.get(i));
        }
        
        ArrayList<String> listDoctor = new ArrayList<>();
        listDoctor = consult.getDoctores();
        
        for(int i = 0; i < listDoctor.size(); i++){
            doctor.addItem(listDoctor.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edad1 = new javax.swing.JComboBox();
        panelConsulta = new javax.swing.JPanel();
        consultDisponibles = new javax.swing.JLabel();
        opcionesConsulta = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        labelPadecimientos = new javax.swing.JLabel();
        labelAreaP = new javax.swing.JLabel();
        labelDoctor = new javax.swing.JLabel();
        labelAreaTrabajo = new javax.swing.JLabel();
        labelCatidadPacientes = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelIdentificacion = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelIntensidad = new javax.swing.JLabel();
        intensidad = new javax.swing.JComboBox();
        labelGenero = new javax.swing.JLabel();
        labelPadecimientoPaciente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        padecimiento = new javax.swing.JComboBox();
        areaPadecimiento = new javax.swing.JComboBox();
        doctor = new javax.swing.JComboBox();
        areaTrabajo = new javax.swing.JComboBox();
        cantidad = new javax.swing.JComboBox();
        identificacion = new javax.swing.JComboBox();
        nombre = new javax.swing.JComboBox();
        edad = new javax.swing.JComboBox();
        genero = new javax.swing.JComboBox();
        telefono = new javax.swing.JComboBox();
        padecimientoPaciente = new javax.swing.JComboBox();
        labelFecha = new javax.swing.JLabel();
        fecha = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        home = new javax.swing.JButton();

        edad1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        consultDisponibles.setText("Consultas disponibles: ");

        opcionesConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elija una opcion", "Area", "Padecimiento", "Doctor", "Paciente", "Cita" }));
        opcionesConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesConsultaActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.setFocusable(false);
        jScrollPane1.setViewportView(Tabla);

        labelPadecimientos.setText("Padecimiento:");

        labelAreaP.setText("Area a la que pertenece:");

        labelDoctor.setText("Doctor:");

        labelAreaTrabajo.setText("Area de Trabajo:");

        labelCatidadPacientes.setText("Cantidad de pacientes por dia");

        labelNombre.setText("Nombre:");

        labelIdentificacion.setText("Identificacion");

        labelTelefono.setText("Telefono");

        labelEdad.setText("Edad");

        labelIntensidad.setText("Intensidad");

        intensidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "bajo", "medio", "alto" }));

        labelGenero.setText("Genero");

        labelPadecimientoPaciente.setText("Padecimiento");

        padecimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Padecimientos" }));

        areaPadecimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Areas" }));

        doctor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doctores" }));

        areaTrabajo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Areas" }));

        cantidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pacientes" }));

        identificacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Identificaciones" }));

        nombre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombres" }));

        edad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Edades" }));

        genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Generos", "masculino", "femenino", "" }));

        telefono.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Telefonos" }));

        padecimientoPaciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Padecimientos" }));

        labelFecha.setText("Fecha de CIta:");

        fecha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fechas" }));

        javax.swing.GroupLayout panelConsultaLayout = new javax.swing.GroupLayout(panelConsulta);
        panelConsulta.setLayout(panelConsultaLayout);
        panelConsultaLayout.setHorizontalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultaLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(consultDisponibles)
                        .addGap(26, 26, 26)
                        .addComponent(opcionesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConsultaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelConsultaLayout.createSequentialGroup()
                                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelConsultaLayout.createSequentialGroup()
                                        .addComponent(labelPadecimientos)
                                        .addGap(29, 29, 29)
                                        .addComponent(padecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelAreaTrabajo))
                                    .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelFecha)
                                        .addComponent(labelDoctor)))
                                .addGap(18, 18, 18))
                            .addGroup(panelConsultaLayout.createSequentialGroup()
                                .addComponent(labelAreaP)
                                .addGap(18, 18, 18)
                                .addComponent(areaPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(labelCatidadPacientes)
                                .addGap(7, 7, 7)))
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(428, 428, 428))
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultaLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelConsultaLayout.createSequentialGroup()
                                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelNombre)
                                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelEdad)
                                            .addComponent(labelGenero)))
                                    .addGroup(panelConsultaLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(labelTelefono)))
                                .addGap(38, 38, 38)
                                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(telefono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelConsultaLayout.createSequentialGroup()
                                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(intensidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(padecimientoPaciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(panelConsultaLayout.createSequentialGroup()
                                .addComponent(labelIdentificacion)
                                .addGap(18, 18, 18)
                                .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConsultaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelIntensidad)
                            .addComponent(labelPadecimientoPaciente))
                        .addGap(217, 217, 217))))
        );
        panelConsultaLayout.setVerticalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultDisponibles)
                    .addComponent(opcionesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIdentificacion)
                            .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEdad)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGenero)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefono)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPadecimientoPaciente)
                            .addComponent(padecimientoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIntensidad)
                            .addComponent(intensidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelConsultaLayout.createSequentialGroup()
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsultaLayout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelConsultaLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFecha)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDoctor)
                            .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPadecimientos)
                            .addComponent(padecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAreaTrabajo)
                            .addComponent(areaTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsultaLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelAreaP)
                                    .addComponent(areaPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelConsultaLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCatidadPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel1.setText("            ");

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        home.setText("ATRÁS");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultar)
                            .addComponent(home))
                        .addGap(32, 32, 32))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesConsultaActionPerformed
        String opcion = (String)opcionesConsulta.getSelectedItem();
        if("Area".equals(opcion)){crearConsultaArea();}
        if("Padecimiento".equals(opcion)){crearConsultaPadecimiento();}
        if("Doctor".equals(opcion)){crearConsultaDoctor();}
        if("Paciente".equals(opcion)){crearConsultaPaciente();}
        if("Cita".equals(opcion)){crearConsultaCita();}
    }//GEN-LAST:event_opcionesConsultaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
         String opcion = (String)opcionesConsulta.getSelectedItem();
        if("Elija una opcion".equals(opcion)){
            JOptionPane.showMessageDialog(null, "No se a elegido ninguna opcion para consultar");
        }
        if("Area".equals(opcion)){
            Query q;
            q= new Query("consult('mantenimiento.pl')");
            System.err.println(q.hasSolution());
            consult.getAreas3();
        }
         if("Padecimiento".equals(opcion)){
            Query q;
            q= new Query("consult('mantenimiento.pl')");
            System.err.println(q.hasSolution());
            consult.getPadecimientosInter(padecimiento.getSelectedItem().toString(), areaPadecimiento.getSelectedItem().toString());
        }
        if("Doctor".equals(opcion)){
            Query q;
            q= new Query("consult('mantenimiento.pl')");
            System.err.println(q.hasSolution());
            consult.getDoctoresInter(doctor.getSelectedItem().toString(),areaTrabajo.getSelectedItem().toString(),cantidad.getSelectedItem().toString());
        } 
        if("Paciente".equals(opcion)){
            Query q;
            q= new Query("consult('mantenimiento.pl')");
            System.err.println(q.hasSolution());
            System.out.println("soy yo"+identificacion.getSelectedItem());
            consult.getDatosPacienteInter(identificacion.getSelectedItem().toString(),nombre.getSelectedItem().toString(),edad.getSelectedItem().toString(),genero.getSelectedItem().toString(),telefono.getSelectedItem().toString(),padecimientoPaciente.getSelectedItem().toString(),intensidad.getSelectedItem().toString());
        }
        if("Cita".equals(opcion)){
        Query q;
        q = new Query("consult('mantenimiento.pl')");
        System.err.println(q.hasSolution());
        String newwwFecha = listaFechas.get(fecha.getSelectedIndex());
        consult.getDatosCitaInter(identificacion.getSelectedItem().toString(),doctor.getSelectedItem().toString(),newwwFecha.toString());
        
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    
    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaConsultas dialog = new VentanaConsultas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabla;
    private javax.swing.JComboBox areaPadecimiento;
    private javax.swing.JComboBox areaTrabajo;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox cantidad;
    private javax.swing.JLabel consultDisponibles;
    private javax.swing.JComboBox doctor;
    private javax.swing.JComboBox edad;
    private javax.swing.JComboBox edad1;
    private javax.swing.JComboBox fecha;
    private javax.swing.JComboBox genero;
    private javax.swing.JButton home;
    private javax.swing.JComboBox identificacion;
    private javax.swing.JComboBox intensidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAreaP;
    private javax.swing.JLabel labelAreaTrabajo;
    private javax.swing.JLabel labelCatidadPacientes;
    private javax.swing.JLabel labelDoctor;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel labelIntensidad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPadecimientoPaciente;
    private javax.swing.JLabel labelPadecimientos;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JComboBox nombre;
    private javax.swing.JComboBox opcionesConsulta;
    private javax.swing.JComboBox padecimiento;
    private javax.swing.JComboBox padecimientoPaciente;
    private javax.swing.JPanel panelConsulta;
    private javax.swing.JComboBox telefono;
    // End of variables declaration//GEN-END:variables

    private void crearConsultaArea() {
        
        
        Tabla.setVisible(true);
        
        labelPadecimientos.setVisible(false);
        padecimiento.setVisible(false);
        labelAreaP.setVisible(false);
        areaPadecimiento.setVisible(false);
        fecha.setVisible(false);
        labelFecha.setVisible(false);
        
        labelDoctor.setVisible(false);
        doctor.setVisible(false);
        labelAreaTrabajo.setVisible(false);
        areaTrabajo.setVisible(false);
        labelCatidadPacientes.setVisible(false);
        cantidad.setVisible(false);
        
        labelIdentificacion.setVisible(false);
        identificacion.setVisible(false);
        labelNombre.setVisible(false);
        nombre.setVisible(false);
        labelEdad.setVisible(false);
        edad.setVisible(false);
        labelGenero.setVisible(false);
        genero.setVisible(false);
        labelTelefono.setVisible(false);
        telefono.setVisible(false);
        labelPadecimientoPaciente.setVisible(false);
        padecimientoPaciente.setVisible(false);
        labelIntensidad.setVisible(false);
        intensidad.setVisible(false);
        

       
        pack();
        setLocationRelativeTo(null);
    }
    
    
    private void crearConsultaPadecimiento(){
        
        Tabla.setVisible(true);
        
        labelPadecimientos.setVisible(true);
        padecimiento.setVisible(true);
        fecha.setVisible(false);
        labelFecha.setVisible(false);
        labelAreaP.setVisible(true);
        
        areaPadecimiento.setVisible(true);
        
        
        labelDoctor.setVisible(false);
        doctor.setVisible(false);
        labelAreaTrabajo.setVisible(false);
        areaTrabajo.setVisible(false);
        labelCatidadPacientes.setVisible(false);
        cantidad.setVisible(false);
        
        labelIdentificacion.setVisible(false);
        identificacion.setVisible(false);
        labelNombre.setVisible(false);
        nombre.setVisible(false);
        labelEdad.setVisible(false);
        edad.setVisible(false);
        labelGenero.setVisible(false);
        genero.setVisible(false);
        labelTelefono.setVisible(false);
        telefono.setVisible(false);
        labelPadecimientoPaciente.setVisible(false);
        padecimientoPaciente.setVisible(false);
        labelIntensidad.setVisible(false);
        intensidad.setVisible(false);
       

        pack();
        setLocationRelativeTo(null);
    }

    private void crearConsultaDoctor() {
        
        Tabla.setVisible(true);
        
        labelPadecimientos.setVisible(false);
        padecimiento.setVisible(false);
        labelAreaP.setVisible(false);
        areaPadecimiento.setVisible(false);
        fecha.setVisible(false);
        labelFecha.setVisible(false);
        
        
        labelDoctor.setVisible(true);
        doctor.setVisible(true);
        labelAreaTrabajo.setVisible(true);
        areaTrabajo.setVisible(true);
        labelCatidadPacientes.setVisible(true);
        cantidad.setVisible(true);
        
        int e = 7;
        
        for(int i = 1; i < e; i++){
            cantidad.addItem(i);
        }
        
        labelIdentificacion.setVisible(false);
        identificacion.setVisible(false);
        labelNombre.setVisible(false);
        nombre.setVisible(false);
        labelEdad.setVisible(false);
        edad.setVisible(false);
        labelGenero.setVisible(false);
        genero.setVisible(false);
        labelTelefono.setVisible(false);
        telefono.setVisible(false);
        labelPadecimientoPaciente.setVisible(false);
        padecimientoPaciente.setVisible(false);
        labelIntensidad.setVisible(false);
        intensidad.setVisible(false);
        

        pack();
        setLocationRelativeTo(null);
    }
    
    
    
    private void crearConsultaPaciente() {
        
        Tabla.setVisible(true);
        labelPadecimientos.setVisible(false);
        padecimiento.setVisible(false);
        labelAreaP.setVisible(false);
        areaPadecimiento.setVisible(false);
        
        fecha.setVisible(false);
        labelFecha.setVisible(false);
        
        
        labelDoctor.setVisible(false);
        doctor.setVisible(false);
        labelAreaTrabajo.setVisible(false);
        areaTrabajo.setVisible(false);
        labelCatidadPacientes.setVisible(false);
        cantidad.setVisible(false);
        
        labelIdentificacion.setVisible(true);
        identificacion.setVisible(true);
        labelNombre.setVisible(true);
        nombre.setVisible(true);
        labelEdad.setVisible(true);
        edad.setVisible(true);
        labelGenero.setVisible(true);
        genero.setVisible(true);
        labelTelefono.setVisible(true);
        telefono.setVisible(true);
        labelPadecimientoPaciente.setVisible(true);
        padecimientoPaciente.setVisible(true);
        labelIntensidad.setVisible(true);
        intensidad.setVisible(true);
        
        
        nombre.removeAllItems();
        nombre.addItem("Nombres");
        identificacion.removeAllItems();
        identificacion.addItem("Identificaciones");
        telefono.removeAllItems();
        telefono.addItem("Telefonos");
        
        ArrayList<String> listaIdentificaciones = new ArrayList<String>();
        listaIdentificaciones = consult.getIdentificacion();
        
        for(int i = 0; i < listaIdentificaciones.size(); i++){
            identificacion.addItem(listaIdentificaciones.get(i));
        }
        
        ArrayList<String> listaNombres = new ArrayList<String>();
        listaNombres = consult.getNombrePaciente();
        
        for(int i = 0; i < listaNombres.size(); i++){
            nombre.addItem(listaNombres.get(i));
        }
        
        int e = 101;
        
        for(int i = 1; i < e; i++){
            edad.addItem(i);
        }
   
        ArrayList<String> listaTelefono = new ArrayList<String>();
        listaTelefono = consult.getTelefono();
        
        for(int i = 0; i < listaTelefono.size(); i++){
            telefono.addItem(listaTelefono.get(i));
        }    
        
    }
    
    
    private void crearConsultaCita() {
        

        labelPadecimientos.setVisible(false);
        padecimiento.setVisible(false);
        labelAreaP.setVisible(false);
        areaPadecimiento.setVisible(false);
        
        labelAreaTrabajo.setVisible(false);
        areaTrabajo.setVisible(false);
        labelCatidadPacientes.setVisible(false);
        cantidad.setVisible(false);
        
        doctor.removeAllItems();
        doctor.addItem("Doctores");
        identificacion.removeAllItems();
        identificacion.addItem("Identificaciones");
        fecha.removeAllItems();
        fecha.addItem("Fechas");
        
        
        ArrayList<String> listaDoctores = new ArrayList<>();
        listaDoctores = consult.getDoctores();
        
        for(int i = 0; i < listaDoctores.size(); i++){
            doctor.addItem(listaDoctores.get(i));
        }
        
        ArrayList<String> listaPac = new ArrayList<>();
        listaPac = consult.getIdentificacion();
        
        for(int i = 0; i < listaPac.size(); i++){
            identificacion.addItem(listaPac.get(i));
        }
        
        listaFechas.clear();
       
        listaFechas = consult.getFechasCita();
         listaFechas.add(0, "Fechas");
        System.out.println(listaFechas);
        
        
        String fechaa;
        ArrayList<String> newListaFechas = new ArrayList<>();

        for(int i = 1; i < listaFechas.size(); i++){
            fechaa = listaFechas.get(i);
            fechaa = fechaa.replace("-","");
            fechaa = fechaa.replace(")","");
            fechaa = fechaa.replace("(","");
            newListaFechas.add(fechaa);
        }
        
        for(int i = 0; i < newListaFechas.size(); i++){
            fecha.addItem(newListaFechas.get(i));
        }
        
        
        labelIdentificacion.setVisible(true);
        identificacion.setVisible(true);
        labelEdad.setVisible(false);
        edad.setVisible(false);
        labelGenero.setVisible(false);
        genero.setVisible(false);
        labelTelefono.setVisible(false);
        telefono.setVisible(false);
        labelPadecimientoPaciente.setVisible(false);
        padecimientoPaciente.setVisible(false);
        labelIntensidad.setVisible(false);
        intensidad.setVisible(false);
        
        
        // objetos que aparecen
        labelDoctor.setVisible(true);
        doctor.setVisible(true);
        
        labelNombre.setVisible(false);
        nombre.setVisible(false);
        
        Tabla.setVisible(true);
        
        fecha.setVisible(true);
        labelFecha.setVisible(true);

    }
    
    
    
    
}


