/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author silvia
 */
public class VentanaMantenimiento extends javax.swing.JDialog {
         Consulta consult = new Consulta();
         Insercion insert = new Insercion();
    /**
     * Creates new form Mantenimiento
     */
    public VentanaMantenimiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        ArrayList<String> listAreas = new ArrayList<String>();
        listAreas = consult.getAreas();
        
        for(int i = 0; i < listAreas.size(); i++){
            areaPadecimiento.addItem(listAreas.get(i));
            areaDoctor.addItem(listAreas.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMantenimiento = new javax.swing.JPanel();
        panelDoct = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nombreDoctor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        agregarDoc = new javax.swing.JButton();
        pacientesDIa = new javax.swing.JLabel();
        cantidad = new javax.swing.JSpinner();
        areaDoctor = new javax.swing.JComboBox();
        panelArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        area = new javax.swing.JTextField();
        btnAgregarArea = new javax.swing.JButton();
        panelPadecimiento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        padecimiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarPadecimiento = new javax.swing.JButton();
        areaPadecimiento = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SAPCI - Mantenimiento de Datos");

        PanelMantenimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimiento de Datos", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        panelDoct.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        jLabel4.setText("Nombre:");

        jLabel6.setText("Área de trabajo:");

        agregarDoc.setText("Agregar Doctor");
        agregarDoc.setFocusPainted(false);
        agregarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDocActionPerformed(evt);
            }
        });

        pacientesDIa.setText("Número de pacientes por día:");

        cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));

        javax.swing.GroupLayout panelDoctLayout = new javax.swing.GroupLayout(panelDoct);
        panelDoct.setLayout(panelDoctLayout);
        panelDoctLayout.setHorizontalGroup(
            panelDoctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoctLayout.createSequentialGroup()
                .addGroup(panelDoctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDoctLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(panelDoctLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(nombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDoctLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDoctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDoctLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(areaDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(panelDoctLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(agregarDoc))
                    .addGroup(panelDoctLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pacientesDIa))
                    .addGroup(panelDoctLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelDoctLayout.setVerticalGroup(
            panelDoctLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoctLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(areaDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pacientesDIa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(agregarDoc)
                .addContainerGap())
        );

        panelArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        jLabel1.setText("Nombre del Área");

        btnAgregarArea.setText("Agregar Área");
        btnAgregarArea.setFocusPainted(false);
        btnAgregarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAreaLayout = new javax.swing.GroupLayout(panelArea);
        panelArea.setLayout(panelAreaLayout);
        panelAreaLayout.setHorizontalGroup(
            panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarArea)
                .addGap(40, 40, 40))
        );
        panelAreaLayout.setVerticalGroup(
            panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarArea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPadecimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Padecimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        jLabel2.setText("Nombre del padecimiento: ");

        jLabel3.setText("Área a la que pertenece: ");

        btnAgregarPadecimiento.setText("Agregar Padecimiento");
        btnAgregarPadecimiento.setFocusPainted(false);
        btnAgregarPadecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPadecimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPadecimientoLayout = new javax.swing.GroupLayout(panelPadecimiento);
        panelPadecimiento.setLayout(panelPadecimientoLayout);
        panelPadecimientoLayout.setHorizontalGroup(
            panelPadecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPadecimientoLayout.createSequentialGroup()
                .addGroup(panelPadecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPadecimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(panelPadecimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(panelPadecimientoLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnAgregarPadecimiento))
                    .addGroup(panelPadecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelPadecimientoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(areaPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPadecimientoLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(padecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPadecimientoLayout.setVerticalGroup(
            panelPadecimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPadecimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(padecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarPadecimiento)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelMantenimientoLayout = new javax.swing.GroupLayout(PanelMantenimiento);
        PanelMantenimiento.setLayout(PanelMantenimientoLayout);
        PanelMantenimientoLayout.setHorizontalGroup(
            PanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMantenimientoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPadecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(panelDoct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        PanelMantenimientoLayout.setVerticalGroup(
            PanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMantenimientoLayout.createSequentialGroup()
                .addGroup(PanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMantenimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMantenimientoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(panelDoct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(PanelMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(PanelMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAreaActionPerformed

        if ("".equals(area.getText())){
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del area");
        }
        else{
            String newArea = area.getText().toLowerCase();
            String areaParse = newArea.replace(" ", "_");
            if (consult.isArea(areaParse)){
                JOptionPane.showMessageDialog(this, "El area ya esta registrada en el sistema");
            }
            else{
                JOptionPane.showMessageDialog(this, "Area de " + newArea + ", agregada correctamente");
                if((insert.setArea(areaParse)));
                areaPadecimiento.addItem(areaParse);
                areaDoctor.addItem(areaParse);
            }
        }    
        area.setText(null);
        
        
    }//GEN-LAST:event_btnAgregarAreaActionPerformed

    private void btnAgregarPadecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPadecimientoActionPerformed
        
        if ("".equals(padecimiento.getText()) || null == areaPadecimiento.getSelectedItem()){
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
                    
        } 
        else{
            String newPadecimiento= padecimiento.getText().toLowerCase();
            if(consult.isPadecimiento(newPadecimiento))
                JOptionPane.showMessageDialog(this, "El padecimiento ya esta registrado en el sistema");
            else{
                 if((insert.setPadecimiento(newPadecimiento,areaPadecimiento.getSelectedItem().toString()))){
                    JOptionPane.showMessageDialog(this, " Padecimiento agregado correctamente");
                } 
            }        
        }  
        padecimiento.setText(null);
        
    }//GEN-LAST:event_btnAgregarPadecimientoActionPerformed

    private void agregarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDocActionPerformed
        
        if ("".equals(nombreDoctor.getText())|| null == areaPadecimiento.getSelectedItem()){
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
        } 
        else{
            String newDoctor= nombreDoctor.getText().toLowerCase();
            if(consult.isDoctor(newDoctor))
               JOptionPane.showMessageDialog(this, "El doctor ya esta registrado en el sistema");
            else{
                if((insert.setDoctor(newDoctor,areaDoctor.getSelectedItem().toString() ,cantidad.getValue().toString()))){
                    JOptionPane.showMessageDialog(this, " Doctor agregado correctamente");
                }
            }    
        }    
    }//GEN-LAST:event_agregarDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaMantenimiento dialog = new VentanaMantenimiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMantenimiento;
    private javax.swing.JButton agregarDoc;
    private javax.swing.JTextField area;
    private javax.swing.JComboBox areaDoctor;
    private javax.swing.JComboBox areaPadecimiento;
    private javax.swing.JButton btnAgregarArea;
    private javax.swing.JButton btnAgregarPadecimiento;
    private javax.swing.JSpinner cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreDoctor;
    private javax.swing.JLabel pacientesDIa;
    private javax.swing.JTextField padecimiento;
    private javax.swing.JPanel panelArea;
    private javax.swing.JPanel panelDoct;
    private javax.swing.JPanel panelPadecimiento;
    // End of variables declaration//GEN-END:variables
}
