/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;

/**
 *
 * @author silvia
 */
public class VentanaAsignacionCita extends javax.swing.JDialog {
     Consulta consult = new Consulta();
         Insercion insert = new Insercion();
         Fecha fdate= new Fecha();

    /**
     * Creates new form VentanaAsignacionCita
     * @param parent
     */
    public VentanaAsignacionCita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAsignacion = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        nombrePaciente = new javax.swing.JTextField();
        idpaciente = new javax.swing.JLabel();
        identificacion = new javax.swing.JTextField();
        edadPaciente = new javax.swing.JLabel();
        generoPaciente = new javax.swing.JLabel();
        genero = new javax.swing.JComboBox();
        telPaciente = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        edad = new javax.swing.JSpinner();
        padecimiento = new javax.swing.JTextField();
        padecimientoPaciente = new javax.swing.JLabel();
        nivelINtensidad = new javax.swing.JLabel();
        nivelIntencidad = new javax.swing.JComboBox();
        btnAsignarCita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SAPCI - Asignacion de Citas");

        panelAsignacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignación de Citas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        nombre.setText("Nombre:");

        idpaciente.setText("Identificación:");

        edadPaciente.setText("Edad:");

        generoPaciente.setText("Género");

        genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "masculino", "fenemino" }));

        telPaciente.setText("Teléfono ");

        edad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 120, 1));

        padecimientoPaciente.setText("Padecimiento:");

        nivelINtensidad.setText("Nivel de intensidad: ");

        nivelIntencidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bajo", "medio", "alto" }));

        btnAsignarCita.setText("Asignar Cita");
        btnAsignarCita.setFocusPainted(false);
        btnAsignarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAsignacionLayout = new javax.swing.GroupLayout(panelAsignacion);
        panelAsignacion.setLayout(panelAsignacionLayout);
        panelAsignacionLayout.setHorizontalGroup(
            panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsignacionLayout.createSequentialGroup()
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsignacionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nivelINtensidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAsignacionLayout.createSequentialGroup()
                        .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAsignacionLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAsignacionLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(idpaciente))
                                    .addComponent(padecimientoPaciente)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsignacionLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edadPaciente)
                                    .addComponent(nombre)
                                    .addComponent(generoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telPaciente))))
                        .addGap(18, 18, 18)))
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nivelIntencidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(identificacion)
                        .addComponent(nombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(padecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addGroup(panelAsignacionLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnAsignarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAsignacionLayout.setVerticalGroup(
            panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignacionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpaciente)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadPaciente)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoPaciente))
                .addGap(20, 20, 20)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telPaciente)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(padecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(padecimientoPaciente))
                .addGap(18, 18, 18)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivelINtensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelIntencidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnAsignarCita)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(panelAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(panelAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCitaActionPerformed
        java.sql.Date fechaTentativa= fdate.getFecha2();
        //java.sql.Date fecha=fdate.sumarFechasDias(fechaTentativa,0);
        //identificacion.setText(fecha.toString());
        String id= identificacion.getText().toString();
        String nom=nombrePaciente.getText().toLowerCase();
        String edadv= edad.getValue().toString();
        String gen=genero.getSelectedItem().toString();
        String tel= telefono.getText().toString();
        String pade=padecimiento.getText().toLowerCase().toString();
        String ni=nivelIntencidad.getSelectedItem().toString();
        
        if ("".equals(identificacion.getText()) || "".equals(nombre.getText())
                  || "".equals(telefono.getText()) ||  "".equals(padecimiento.getText())){
            JOptionPane.showMessageDialog(this, "Datos incorrectos");
        }
        else{
        
              if(consult.isPaciente(id)){
            JOptionPane.showMessageDialog(this, "El paciente ya existe");
              } 
            
        else{
                     if(consult.isPadecimiento(pade)){
                         if((insert.setPaciente(id,nom,edadv,gen,tel,pade,ni))); {
                         JOptionPane.showMessageDialog(this, "Paciente ingresado satisfactoriamente");
                         String msj=insert.determinarCita(fechaTentativa, id, pade, ni);
            JOptionPane.showMessageDialog(this,msj);
                     }
          
                    }
                     else{
                           JOptionPane.showMessageDialog(this, "El padecimiento no existe");
                     }
              
        }
        }//cierre else grande
              identificacion.setText(null);
              nombrePaciente.setText(null);
              telefono.setText(null);
              padecimiento.setText(null);
              
    }//GEN-LAST:event_btnAsignarCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAsignacionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAsignacionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAsignacionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAsignacionCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaAsignacionCita dialog = new VentanaAsignacionCita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarCita;
    private javax.swing.JSpinner edad;
    private javax.swing.JLabel edadPaciente;
    private javax.swing.JComboBox genero;
    private javax.swing.JLabel generoPaciente;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel idpaciente;
    private javax.swing.JLabel nivelINtensidad;
    private javax.swing.JComboBox nivelIntencidad;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombrePaciente;
    private javax.swing.JTextField padecimiento;
    private javax.swing.JLabel padecimientoPaciente;
    private javax.swing.JPanel panelAsignacion;
    private javax.swing.JLabel telPaciente;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
